build:
  nodes:
    analysis:
      dependencies:
        before:
          - composer require --dev johnpbloch/wordpress
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run --standard=phpcs.ruleset.xml
filter:
    dependency_paths:
        - wordpress/
    excluded_paths: [vendor/*, tests/*, .tx/*, languages/*, includes/libraries/*, bin/*, assets/*, templates/* ]
checks:
    php:
        code_rating: true
